version: "3.5"
services:
  web-server:
    build:
      dockerfile: ./php.Dockerfile
      context: .
    restart: 'no'
    volumes:
      - "./src/:/var/www/html/"
    ports:
      - "8080:80"

  mongo:
    image: mongo:4.4
    restart: 'no'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - "./mongodata:/data/db"

volumes:
  mongo-data:



